### PR TITLE
fix: Nomination message now checks historic and new style nominations

### PR DESCRIPTION
**Pull request by ChrisLovering**
Previously nomination messages had role pings in them, now they don't as we moved them into a thread.
Due to this, we need to detect both styles of message in the interim of historic nominations existing.

A 'proper' fix for this is to store the nomination message IDs when we post them against the
nomination object in the site api. We are planing to work on this soon, this commit is a
short term fix.

### CODE REVIEW

**Review by wookie184 — APPROVED** [review]
Looks good to me

**Comment by ChrisLovering** [comment]
Ran into a bug where it would delete all messages in the channel under some circumstances...investigating a fix

**Comment by ChrisLovering** [comment]
Ok, false alarm. The issue was caused due to me copying the text from another nomination to test, rather than using post_review or get_review. Due to this, the message contained a bunch of spaces that caused the regex to fail. This would also happen with the current system, so the proper fix is to upgrade to storing the message IDs, rather than use regex. This will do for now though.

**Review by wookie184 — APPROVED** [review]
Dunno if there's any need for approving again, but I will anyway, lgtm!

**Review by Akarys42 — APPROVED** [review]

**Pull request merged**
