### PR TITLE
Migrate to Pydantic v2

### PR DESCRIPTION
**Pull request by ChrisLovering**
### Summary
All commits starting with `breaking:` are breaking changes from Pydantic and will be squashed into 1 commit before merging. (Hence the do not merge tag)

Other commits are kaizen style commits that I noticed while working on this PR.

This will be far easier to review commit-by-commit.

### Todo:
Squash commits before merging

### CODE REVIEW

**Comment by shtlrs** [comment]
image

**Comment by ChrisLovering** [comment]
> > Required investigation
> > I have not investigated if @field_validator("_", mode="before") works the same as @validator("_", pre=True) as far as the "*" is concerned to run the validator on all fields. relevant commit: [46bf3cc](https://github.com/python-discord/bot/commit/46bf3cc3daca24981f915f6518702a9b00b4c0af)
> 
> According to their docs, it looks like a wildcard will do the job. image

Ah nice, thanks.

**Review by wookie184 — APPROVED** [review]
🚀

**Review by shtlrs — APPROVED** [review]
Great work.

Would you like to do the same thing as 3a279b3d3faa679684a5b1bb5abda925abf16c38 for `Colours` and `Emojis`, I don't think these are things that anyone will ever configure, i don't even see the use of configuring them. (Might as well look into other classes that we ourselves do not quite setup)

**Comment by ChrisLovering** [comment]
> Great work.
> 
> Would you like to do the same thing as [3a279b3](https://github.com/python-discord/bot/commit/3a279b3d3faa679684a5b1bb5abda925abf16c38) for `Colours` and `Emojis`, I don't think these are things that anyone will ever configure, i don't even see the use of configuring them. (Might as well look into other classes that we ourselves do not quite setup)

I didn't touch colours as it has the validator, but that just seems to convert hexstrings into ints, so that might be something we can move to a basic class. Emojis needs to stay he same way as it is, mostly for the trash & incidents emojis.

**Pull request merged**
