### PR TITLE
AntiSpam Mute Infraction

### PR DESCRIPTION
**Pull request by sco1**
Addresses the remaining item in #148: Utilizes a temporary mute infraction rather than having the mute be totally contained by the AntiSpam coro, preventing non-administrators from removing the muted role in the event of a false-positive.

~~Because I'm having issues getting the local site/bot deployment working, this is considered a WIP until it can be tested by either myself or another contributor.~~

Closes: #148

### CODE REVIEW

**Comment by sco1** [comment]
Antispam now directly invokes the Moderation cog's `tempmute` so the infraction is reversible. This also gives the added benefit of not having to maintain essentially the same infraction code in two separate cogs.

image
image

**Comment by GhostofGoes** [comment]
@sco1 Could you resolve the conflicts?

**Comment by sco1** [comment]
Done

**Comment by GhostofGoes** [comment]
@SebastiaanZ Can you approve the conflict resolution changes?

**Pull request merged**
