### PR TITLE
reply to user when using !eval/!timeit command instead of pinging

### LINKED ISSUE #2382: Reply to !eval message instead of pinging
It was discussed in [#community-meta](https://discord.com/channels/267624335836053506/429409067623251969/1064000890798870558) if the `!eval` command should reply to the original command instead of sending a separate message with a ping. Thoughts on this? I'd be willing to PR if accepted.

### PR DESCRIPTION
**Pull request by e1pupper**
Closes #2382 

Just needed to change ctx.send to ctx.reply and remove the author.mention.

### CODE REVIEW

**Comment by n0Oo0Oo0b** [comment]
> bot/issues/2382
> 
> Just needed to change ctx.send to ctx.reply and remove the author.mention.

What if the response gets redirected to a different channel? `@redirect_output()` doesn't change the behavior of `ctx.reply()` so the result won't be redirected when it should.
It may be worth considering having `@redirect_output()` add an extra bool attribute (maybe `redirected`?) for whether or not the output was redirected or maybe even replacing the `ctx.reply()` function to send a message to the redirected channel instead (not sure if replacing `ctx.reply()` would be a good idea though).

**Comment by e1pupper** [comment]
> > bot/issues/2382
> > Just needed to change ctx.send to ctx.reply and remove the author.mention.
> 
> What if the response gets redirected to a different channel? `@redirect_output()` doesn't change the behavior of `ctx.reply()` so the result won't be redirected when it should. It may be worth considering having `@redirect_output()` add an extra bool attribute (maybe `redirected`?) for whether or not the output was redirected or maybe even replacing the `ctx.reply()` function to send a message to the redirected channel instead (not sure if replacing `ctx.reply()` would be a good idea though).

I just looked into the `@redirect_output()` i think it's also sensibile to change those to `.reply()` as well

```py
            if ping_user:
                await ctx.send(f"Here's the output of your command, {ctx.author.mention}")
            scheduling.create_task(func(self, ctx, *args, **kwargs))

            message = await old_channel.send(
                f"Hey, {ctx.author.mention}, you can find the output of your command here: "
                f"{redirect_channel.mention}"
            )
```

**Review by wookie184 — CHANGES_REQUESTED** [review]
We need to handle the case where the message is deleted before the bot sends the response. Currently an error is raised:
image
To reproduce, run `!e import time;time.sleep(5)` and immediately delete your message.

There are three main options I can think of for handling this case:
1. Catch the error and send no response
1. Catch the error and resend the message with a ping instead of a reply
1. Make it so the error isn't raised and the message is just sent without being a reply (and without a ping). (I can't remember exactly how you do this, something to do with https://discordpy.readthedocs.io/en/stable/api.html?highlight=reply#discord.Message.to_reference with `fail_if_not_exists=False`).

I don't have much of a preference given this is an edge case.

**Comment by ChrisLovering** [comment]
> I just looked into the @redirect_output() i think it's also sensibile to change those to .reply() as well

You can only reply to messages in the same channel, so if this message gets redirected to another channel (such as bot-commands in this case) the message in bot-commands you can no longer reply to the original message.

**Comment by e1pupper** [comment]
> We need to handle the case where the message is deleted before the bot sends the response. Currently an error is raised: image To reproduce, run `!e import time;time.sleep(5)` and immediately delete your message.
> 
> There are three main options I can think of for handling this case:
> 
> 1. Catch the error and send no response
> 2. Catch the error and resend the message with a ping instead of a reply
> 3. Make it so the error isn't raised and the message is just sent without being a reply (and without a ping). (I can't remember exactly how you do this, something to do with https://discordpy.readthedocs.io/en/stable/api.html?highlight=reply#discord.Message.to_reference with `fail_if_not_exists=False`).
> 
> I don't have much of a preference given this is an edge case.

i see im gonna see if i can work on this in the weekend sorry for the late response

**Comment by Robin5605** [comment]
So, what's the planned behavior for redirected output? Since those can't reply to the original message.
Perhaps a link button in the original `!eval` that links to the message in `#bot-commands`, and a link button in the result message sent in `#bot-commands`, that links back to the original `!eval` command?

**Comment by Robin5605** [comment]
Oh, and also, @e1pupper had noticed us that they will not be able to work on this. I'd be willing to take this up.

**Comment by wookie184** [comment]
> I'd be willing to take this up.

Sounds good, i've assigned you

**Comment by wookie184** [comment]
I'll take this over. If the response is redirected I'll just keep the old behaviour of mentioning the user.

**Comment by wookie184** [comment]
Since the conflicts are due to the entire snekbox.py file being split up, as this PR is fairly small, I'm just going to start over on a new branch.

**Pull request closed without merging**
