### PR TITLE
Change pep command to use `.txt` by default

### PR DESCRIPTION
**Pull request by larswijn**
The pep command would assume either .txt or .rst, which was not always correct. It now always tries both, and should still error the same way when the pip was not found. This is the 2nd time this pull request has been opened because the write history of the previous one had been destroyed.

Closes: #367

### CODE REVIEW

**Comment by jchristgit** [comment]
Couldn't we first try to fetch it by the current logic:
```py
        if pep_number > 542:
	            pep_url = f"{self.base_github_pep_url}{pep_number:04}.rst"
	        else:
	            pep_url = f"{self.base_github_pep_url}{pep_number:04}.txt"
```
and fall back to the other filetype if one returns 404?

**Comment by larswijn** [comment]
You could, but... I personally don't see a reason to do so:
Up until pep 542 almost all of the peps are in `.txt` format, and after pep 542, they're equally split between `.rst` and `.txt`. It would be useful to start with the `.txt` extension first, since that one comes up a lot more often, which would be a simple case of switching around the order that's tried which is just a list in the code.

**Comment by lemonsaurus** [comment]
Yeah, it's weird that we're trying it in the wrong order currently. Sounds like the right approach is:

1. try `.txt`
2. If and only if this fails, try `.rst`

this would lead to far fewer requests, but it would take twice as long to resolve the `.rst` ones because of 2 sequential requests. However, I don't think it'll take so long that most people will notice or mind, so I think that's fine.

**Comment by scragly** [comment]
@larswijn Would you like to revisit this if you get some time.

**Comment by larswijn** [comment]
Updated, should be finished now.

**Pull request merged**
