### PR TITLE
Display whether DM was sent to user when listing infraction(s).

### LINKED ISSUE #1864: Add `DM Sent` field to infraction details
It was [suggested on discord](https://discord.com/channels/267624335836053506/775413915391098921/896283372958134283) by @codephile1221 that when viewing an infraction via the `!infraction` command, it should have a `DM Sent` field for reference -- particularly helpful in the case of a warning as the user may not even realise they were warned for a certain behaviour.

This will require a PR to site since means updating the database schema.

**RELEVANT PR TO BE MERGED WITH THOSE OF [site#610](https://github.com/python-discord/site/issues/610) and [api#20](https://github.com/python-discord/api/issues/20).**

### PR DESCRIPTION
**Pull request by TizzySaurus**
Closes #1864.

The `!infraction` embed now show whether or not a DM was sent when an infraction was made.

Possible values:
- `Yes`: the DM was sent
- `No`: the DM wasn't sent (triggers for "hidden" infractions too)
- `N/A`: the infraction was made before database change so we don't know if DM was sent or not

NOTE: I've not been able to test that the `N/A` actually works since I didn't have any prior infractions in the database, but it *should* be fine.

**Relevant other PRs: [site#621](https://github.com/python-discord/site/pull/621) and [api#28](https://github.com/python-discord/api/pull/28).**

### CODE REVIEW

**Comment by TizzySaurus** [comment]
For the record I'm planning to fix this tests at some point this upcoming week :+1:

**Review by jchristgit — APPROVED** [review]
Rock solid.

**Review by onerandomusername — APPROVED** [review]
lgtm

**Review by jb3 — APPROVED** [review]
Looks good to me!

**Pull request merged**
