### PR TITLE
Add handling of off-server users to user command

### PR DESCRIPTION
**Pull request by mbaruh**
This addresses point 5 in https://github.com/python-discord/bot/issues/654

How it looks like currently:
image

How it will look like:
image

I wonder if it stands out enough. A moderator might miss the fact that they're not on the server.

### CODE REVIEW

**Comment by mbaruh** [comment]
Just to make sure, this doesn't close the issue. I will be working on point 1 after a future PR from @scragly is merged

**Comment by MarkKoz** [comment]
This won't be too effective since the user convert only looks at the cache. Chances are that if the user is not in the guild, they won't be in the cache. Maybe briefly after they get banned or leave, but this won't be the case once the bot restarts. There is a custom `FetchedUser` converter which addresses that problem.

**Comment by mbaruh** [comment]
I used it on a user that was never on the server and it seemed to work without a problem

**Comment by MarkKoz** [comment]
After checking out and running it locally, I can confirm it does not work:

bild

**Comment by mbaruh** [comment]
Thanks, should be fixed

**Review by MarkKoz — APPROVED** [review]

**Review by Numerlor — APPROVED** [review]

**Pull request merged**
