### PR TITLE
Implement showing filterlist entry comment in alerts

### LINKED ISSUE #1394: Mention the reason on watchlist triggers
We have quite a few watchlist triggers, such as regexes and domains which will ping the moderators when someone post a message matching our denylist. 

One of the issue we are currently facing is that it can be hard to know why we watch that particular word or domain. We already allow adding reasons when adding filters to our denylist, but we don’t display them when pinging the mods. We should totally do that!

### PR DESCRIPTION
**Pull request by ks129**
Closes #1394 

This PR make filtering functions returning reason about triggered entry what will be shown in main embed (except for guild invites what show this in guild info embed):
GH-Guild-Blacklist
GH-URL-blacklist

### CODE REVIEW

**Review by kosayoda — CHANGES_REQUESTED** [review]
Couple comments:
1. There are a few missed conditional branches for filters that do not return a reason:
https://github.com/python-discord/bot/blob/81af0099ffd552aa5cb2a61de30cf7bd16a013eb/bot/exts/filters/filtering.py#L435
https://github.com/python-discord/bot/blob/81af0099ffd552aa5cb2a61de30cf7bd16a013eb/bot/exts/filters/filtering.py#L448
https://github.com/python-discord/bot/blob/81af0099ffd552aa5cb2a61de30cf7bd16a013eb/bot/exts/filters/filtering.py#L497

2. The majority of filters do not document the second return value, it'll be nice to have some form of documentation.

Good job overall :+1:

**Comment by mbaruh** [comment]
Why do invites need a special case?

**Comment by ks129** [comment]
@mbaruh If one message contains many invites, then every invite is posted as a separate embed. Reasons is a different for every guild blacklist entry (I suppose). But sure, I'll change wording.

**Review by mbaruh — COMMENTED** [review]
Can you move the reason for invites to the footer as well?

**Comment by ks129** [comment]
@mbaruh Do you mean something like: `Guild ID: ... | Reason: ...`?

**Comment by mbaruh** [comment]
@ks129 yeah. Maybe the other way around

**Comment by ks129** [comment]
@mbaruh Moved guild reason to footer

**Comment by mbaruh** [comment]
Always returning None by certain functions, only to match the signature of other unrelated functions seems a bit iffy to me. I'm wondering if it's better to not unpack the return value right away and check if the return value is a tuple.

**Comment by ks129** [comment]
@mbaruh Now this doesn't have compatibility None returns anymore.

**Review by mbaruh — APPROVED** [review]
Seems to be working as intended.

**Review by Xithrius — APPROVED** [review]
It works very well.

**Review by kosayoda — APPROVED** [review]

**Pull request merged**
