### PR TITLE
Add New Celebrities to `!superstarify`.

### PR DESCRIPTION
**Pull request by dawnofmidnight**
Add new celebrities like Rick Astley to `!superstarify`.

*This was draftified after because we want to add multiple names in a single pr.*

### CODE REVIEW

**Comment by Akarys42** [comment]
Let’s keep this PR open and add more names on this one.

**Comment by AnkithAbhayan** [comment]
Guido Van Rossum

**Comment by dawnofmidnight** [comment]
> Let’s keep this PR open and add more names on this one.

I made it a draft to leave it up for discussion

**Comment by AnkithAbhayan** [comment]
darude

**Comment by OculusMode** [comment]
"John Lennon",
"Ringo Starr",
"George Harrison"

**Comment by Kronifer** [comment]
The Weeknd and Tom from MySpace please

**Comment by Akarys42** [comment]
I don’t like Tom from MySpace as he isn’t really a star, I don’t mind the others. Do you wanna add them @dawnofmidnight ?

**Comment by dawnofmidnight** [comment]
Sure!

**Comment by dawnofmidnight** [comment]
Committed.

**Review by Akarys42 — APPROVED** [review]

**Review by anand2312 — APPROVED** [review]

**Review by vcokltfre — APPROVED** [review]

**Review by Xithrius — APPROVED** [review]

**Review by ChrisLovering — APPROVED** [review]

**Pull request merged**
