### PR TITLE
Rewording botvars.md tag

### PR DESCRIPTION
**Pull request by Hunter2807**
There are still edits to be done, which were suggested by the other reviewer. For now, I just renamed the file to `botvar`. This PR is a continued version of #1784 . More information here -> https://github.com/python-discord/bot/pull/1784#issuecomment-906967074

### CODE REVIEW

**Comment by Xithrius** [comment]
@Hunter2807 Will you be able to do the changes requested by the reviews in the previous PR?

**Comment by Hunter2807** [comment]
Well I had written a comment on the old PR, but a reply hasn't come till now from the reviewer. I think we should just wait until he answers...

**Comment by Xithrius** [comment]
> Well I had written a comment on the old PR, but a reply hasn't come till now from the reviewer. I think we should just wait until he answers...

I've pinged them. And now we wait.

**Comment by Hunter2807** [comment]
There, I have made the requested changes

**Comment by Xithrius** [comment]
Hey @Hunter2807, be sure to read [this guide](https://pythondiscord.com/pages/guides/pydis-guides/contributing/contributing-guidelines/supplemental-information/#writing-good-commit-messages) to improve your commit messages!

**Review by swfarnsworth — APPROVED** [review]
Thanks!

**Pull request merged**
