### PR TITLE
Sentence-cased notification strings

### PR DESCRIPTION
**Pull request by PythonTryHard**

### CODE REVIEW

**Comment by jb3** [comment]
This PR looks good, and a basic grep of the code seems that there are no other capitalisation issues.

However, the other place where this seems to be the case is in the infraction system.

Screenshot 2020-10-31 at 15 20 12

**Comment by PythonTryHard** [comment]
That's a lotta infractions... /s

**Review by MarkKoz — APPROVED** [review]
While there may capitalisation inconsistencies anywhere, that's no reason to hold up the PR. Feel free to fix the rest if you wish, but you don't have to.

**Comment by PythonTryHard** [comment]
I absolutely forgot about this. November was a mess of schoolwork on my end.

**Comment by PythonTryHard** [comment]
GIven the stale-ness of the PR as well as how outdated the branch is, I'm opting for closing this PR and restart on a fresh one when I'm not haunted by real-life issues.

**Pull request closed without merging**
