### PR TITLE
Improve Filter Rerun Logic

### LINKED ISSUE #1934: Don't trigger filters on pin
The filters are re-run on messages that are edited and pinned. Because of the help channel system, This can cause a filter to trigger twice if the opening message contains a trigger.

We should check what causes the filters to trigger on pins and see if there's a way to disable that.

### PR DESCRIPTION
**Pull request by TizzySaurus**
Closes #1934.

Will now only rerun filters in `on_message_edit` if the content or attachments of a message changed. This stops reruns for removal of embeds, change in pin status, etc.

### CODE REVIEW

**Review by HassanAbouelela — APPROVED** [review]

**Comment by Qwerty-133** [comment]
This would not alert us when an embed has been added to a message, which is why we should only really be skipping the filters if the message was pinned or unpinned.

**Comment by TizzySaurus** [comment]
> This would not alert us when an embed has been added to a message, which is why we should only really be skipping the filters if the message was pinned or unpinned.

We don't want to be alerted of that, since it means we'll get double-pinned for domain filters

**Comment by Qwerty-133** [comment]
We might miss self-bots though.

**Comment by HassanAbouelela** [comment]
This is only for message edits, can you actually edit an embed in?

**Comment by Qwerty-133** [comment]
Yep, you can

**Comment by TizzySaurus** [comment]
> We might miss self-bots though.

I believe we have other filters for that

**Comment by Qwerty-133** [comment]
The reason we got two pings for that mod-alert is because of an oversight in the embed filter. So we should be running our filters on embed additions, I can PR a fix for the embed filter.

**Comment by TizzySaurus** [comment]
> We should be running our filters on embed additions. I can PR a fix for the embed filter.
> 
> #1938 relevant issue.

@Qwerty-133 This has been addressed :+1:

**Review by Qwerty-133 — APPROVED** [review]
Everything looks good to me, thanks!

**Pull request merged**
