### PR TITLE
Close voice channels with defcon shutdown

### PR DESCRIPTION
**Pull request by onerandomusername**
## Description

Simple addition to remove the connect permission from the everyone role and restore it when done.

## Reasoning

Keep people from joining voice channels during a raid, making the entire server as read only as it can get.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Review by dawnofmidnight — APPROVED** [review]
LGTM! :shipit:

**Review by ChrisLovering — COMMENTED** [review]
If we're going for shutting down voice channels, should we set `speak` to False too?

We could also take it a step further and kick people from VCs too.

**Comment by onerandomusername** [comment]
> 
> 
> If we're going for shutting down voice channels, should we also set `speak` to False too?

No, because if you can't connect to a voice channel, you can't talk in them.

**Comment by ChrisLovering** [comment]
> > If we're going for shutting down voice channels, should we also set `speak` to False too?
> 
> No, because if you can't connect to a voice channel, you can't talk in them.

I'm referring to users who are already in voice channels.

**Comment by onerandomusername** [comment]
> 
> 
> > > If we're going for shutting down voice channels, should we also set `speak` to False too?
> > 
> > 
> > No, because if you can't connect to a voice channel, you can't talk in them.
> 
> I'm referring to users who are already in voice channels.

If they're already in voice channel, permissions aren't applied until one leaves and rejoins. To fix this, the bot would need to recurse through everyone in the voice channels and disconnect them from the channels.

**Comment by dawnofmidnight** [comment]
> > > > If we're going for shutting down voice channels, should we also set `speak` to False too?
> > > 
> > > 
> > > No, because if you can't connect to a voice channel, you can't talk in them.
> > 
> > 
> > I'm referring to users who are already in voice channels.
> 
> If they're already in voice channel, permissions aren't applied until one leaves and rejoins. To fix this, the bot would need to recurse through everyone in the voice channels and disconnect them from the channels.
> 
> I'm not sure we have the presence intent to get everyone in the voice channels and the ratelimits to remove them. Previously, staff has deleted the voice channels, which would be another possible solution to remove everyone at once.

Why not just hide voice channels?

**Comment by ChrisLovering** [comment]
> > > > If we're going for shutting down voice channels, should we also set `speak` to False too?
> > > 
> > > 
> > > No, because if you can't connect to a voice channel, you can't talk in them.
> > 
> > 
> > I'm referring to users who are already in voice channels.
> 
> If they're already in voice channel, permissions aren't applied until one leaves and rejoins. To fix this, the bot would need to recurse through everyone in the voice channels and disconnect them from the channels.
> 
> I'm not sure we have the presence intent to get everyone in the voice channels and the ratelimits to remove them. Previously, staff has deleted the voice channels, which would be another possible solution to remove everyone at once.

We have the intent, but agreed, it's not worth the effort of iterating through connected members and kicking them.

**Review by ChrisLovering — APPROVED** [review]

**Review by vcokltfre — APPROVED** [review]

**Comment by Akarys42** [comment]
Hey @onerandomusername, thanks for the PR! It seems like you don't say *why* those changes were made. Chris pointed me to the discussion in `#dev-contrib` from last time, if you could mention it on your next PRs that'd be perfect!

**Review by Akarys42 — APPROVED** [review]
🚀

**Pull request merged**
