### PR TITLE
Strip gotcha tag

### PR DESCRIPTION
**Pull request by Shom770**
This pull request adds a strip-gotcha tag, which represents the "gotcha" that a lot of people face with `strip` where they might expect it to remove a suffix/prefix and that it interprets its argument like a substring when it interprets it like a set of characters.

An example:
```py
>>> "Monty Python".strip(" Python")
"M"
```

<h3>Changes</h3>

- Adds a strip-gotcha tag

### CODE REVIEW

**Comment by Akarys42** [comment]
image

**Review by jchristgit — APPROVED** [review]
Cool and good tag. Ran into this a bunch of times myself.

**Comment by vcokltfre** [comment]
May be worth noting that removesuffix is a fairly recent addition

**Comment by Shom770** [comment]
> May be worth noting that removesuffix/removeprefix is a fairly recent addition

How about under the doc links it says "Note: `str.removeprefix` and `str.removesuffix` were added in Python 3.9 and are fairly new"

**Comment by mbaruh** [comment]
The embed already says they were added in 3.9 though

**Review by onerandomusername — COMMENTED** [review]
What about telling the author how to do it if they're using 3.8 or lower?

**Comment by Shom770** [comment]
> The embed already says they were added in 3.9 though

Oh wait, I missed it while reading

**Comment by Shom770** [comment]
> What about telling the author how to do it if they're using 3.8 or lower?

Hmm, that's mentioned in the documentation I believe, and that might make the embed a little long. How about adding that next to the footnote at the bottom?

**Pull request merged**
