### PR TITLE
Account for defcon threshold being None when displaying server info

### PR DESCRIPTION
**Pull request by MarkKoz**
Fixes [BOT-XK](https://sentry.io/organizations/python-discord/issues/2264325856).

### CODE REVIEW

**Comment by mbaruh** [comment]
This works as a fix for the server command, but there's an underlying issue which is that `self.threshold` is set to None by default, but then becomes an empty `relativedelta()` upon reset. My plan was to replace the None's with a `relativedelta()`, as it is apparently false-y anyway, and then it's possible it's not needed to change the server command.

**Comment by MarkKoz** [comment]
Yeah you could avoid it being None, but it still seemed to be an intentional choice to display the dash character rather than "0 days", so that is what I stuck to here.

**Review by mbaruh — APPROVED** [review]
Yeah that seems reasonable

**Review by Akarys42 — APPROVED** [review]
Lgtm

**Pull request merged**
