### PR TITLE
Proposed alternative "available help channel" message.

### PR DESCRIPTION
**Pull request by swfarnsworth**
Having spent more time in the help channels lately, I don't think the "available help channel" message is having the intended effect. I suggest this version, which eliminates the part explaining that the channel will be allocated specifically for the one user (I think everyone knows this or infers as much), and more directly instruct them not to "ask to ask" and to avoid posting code as screenshots.

image

The proposed wording is arguably less friendly, but I don't think this will be an issue if the people who help them are friendly, and I think those who are helping will be more friendly if the questions being posted are easier to jump into.

@Xithrius, perhaps we can discuss this at the staff meeting tomorrow?

### CODE REVIEW

**Comment by Xithrius** [comment]
> @Xithrius, perhaps we can discuss this at the staff meeting tomorrow?

@swfarnsworth Yes.

**Comment by swfarnsworth** [comment]
We discussed a few adjustments during the meeting today. I'll update this PR as I am able.

**Comment by SebastiaanZ** [comment]
The staff meeting seems to agree on this rewording of the first bullet point:

> Ask your Python question, not if you can ask or if there's an expert who can help.

Another point that came up is shortening the first paragraph to just "Send your question here to claim the channel."

The result could be:

> **Send your question here to claim the channel.**
> 
> **Keep in mind**
> • Ask your Python question, not if you can ask or if there's an expert who can help.
> • Provide a code sample as text and the error message, if you have one.
> • Explain what you expect to happen and then what actually happens.
> 
> For more tips, check out our guide on **[asking good questions](https://pythondiscord.com/pages/asking-good-questions/)**.

**Comment by swfarnsworth** [comment]
image

@SebastiaanZ this is what I'd like to merge, though as it differs slightly from what is in your previous comment, feel free to veto.

**Comment by SebastiaanZ** [comment]
I don't mind this solution. My personal preference would be to not emphasize those first words, but I also don't mind it.

Is not holding the Asking Good Questions link intentional?

**Comment by swfarnsworth** [comment]
Regarding the guide not being bolded, I think the fact that it's hyperlinked draws enough attention to it.

**Review by Akarys42 — APPROVED** [review]
Lgtm, thanks Stel!

**Review by ToxicKidz — APPROVED** [review]
:shipit:

**Pull request merged**
