### PR TITLE
discord.py 1.3.x Functionality Migrating

### PR DESCRIPTION
**Pull request by ks129**
To-do list:

- [x] Commands directly awaiting: From `await ctx.invoke` to `await cmd(ctx, ...)`.
- [x] Use `discord.utils.sleep_until`.
- [x] Use `Context.send_help`
- [x] Remove unnecessary [patch](https://github.com/python-discord/bot/blob/master/bot/patches/message_edited_at.py) 
- [x] Use `Message.clear_reaction(emoji)`.

When you have any ideas, what should be added, post them to #734 . I'll regularly check this issue to see is anything new added. Check [changelog](https://discordpy.readthedocs.io/en/latest/whats_new.html#changelog)

### CODE REVIEW

**Comment by ks129** [comment]
Can anyone check, am I missed something somewhere? Basically, all that I know is ready (this `get` vs `fetch` should it's own issue/PR). I also found this is not waiting for help command PR: everything works currently too:
Screenshot 2020-04-03 at 19 55 55
So I'm taking this out of draft and reviewing can start. Sorry when I included some commits here that shouldn't be here.

**Comment by ks129** [comment]
@MarkKoz Now PR that blocked this is merged.

**Comment by ks129** [comment]
Conflicts is now solved for this PR.

**Review by Senjan21 — APPROVED** [review]
Looks good

**Review by jb3 — APPROVED** [review]
Works fine locally, good stuff.

**Pull request merged**
