### PR TITLE
General moderation improvements

### LINKED ISSUE #1278: Short aliases for infraction editing
At the moment, !infr edit last or !infr edit l is the fastest way to amend a previous infraction. Similar to #1170, but more limited in scope. Something like `!i e l` would be nice, if doable, if not `!infr e l` or even `!iel`.

### PR DESCRIPTION
**Pull request by mbaruh**
This PR implements some small but useful changes which were discussed internally:

* Removes the unnecessary and undesired `shadowkick` and `shadowmute` infractions.
* Gives mutes a one hour default duration.
* Adds the `i` alias to the infraction command group, and the `e` alias to the `edit` infraction subcommand, which closes #1278

### CODE REVIEW

**Review by Den4200 — CHANGES_REQUESTED** [review]
I don't think we want to keep `!shadowtempban` either - it can probably be removed as well.
https://github.com/python-discord/bot/blob/7b3d8ed6e655b787c2538541ca35301f2fadb508/bot/exts/moderation/infraction/infractions.py#L201-L225

**Comment by SebastiaanZ** [comment]
I'd like to keep shadowtempban. It's the one that was actually being used from time to time in case we want to tempban someone who's just left the server.

Since it was actually being used, I'd rather not remove it
 There's no harm in keeping it.

**Review by Den4200 — APPROVED** [review]
Looks good to me.

**Review by ks129 — APPROVED** [review]
Looks good for me!

**Pull request merged**
