### PR TITLE
Removed italics from the help command

### PR DESCRIPTION
**Pull request by Ibrahim2750mi**
#2263

### CODE REVIEW

**Comment by Ibrahim2750mi** [comment]
### Should be changed

In these the title(or name) of the description uses bold which is fine by me, could remove the italics from their description if it is agreed upon:
+ https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L415
+ https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L375
+ https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L334

### Shouldn't be changed 

I think in these it is fine to use both bold or italics:
+ https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L26
+ https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L303

**Comment by Ibrahim2750mi** [comment]
@MarkKoz should I make another commit according to my comment I posted or should I wait until some further discussion?

**Comment by MarkKoz** [comment]
> @MarkKoz should I make another commit according to my comment I posted or should I wait until some further discussion?

It's up to you. But if you do, you may end up needing to revert some or all of it depending on the conclusion. If you provide pictures of each output that has/had italics, it would help gather opinions.

**Comment by Ibrahim2750mi** [comment]
@MarkKoz 

Line number edit | Before | After
---|---|---
[Cog description #L375](https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L375) |  | 
[Brief command detail #L334](https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L334) |  | 
[Category description #L415](https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L415) |  | 
[Command description #L310](https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L310) |  | 

Couldn't do this for the below because don't how to trigger these:
+ https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L26
+ https://github.com/python-discord/bot/blob/9b5f2f67b5cdd0ee427607c94e47cfbc394b286f/bot/exts/info/help.py#L303

**Comment by wookie184** [comment]
I think all the changes so far are improvements, I definitely think not being in italics makes reading longer text cleaner and easier.

RE the two that you couldn't trigger, I think they could be left as is and this changed to be italics:
https://github.com/python-discord/bot/blob/dc9cb7910040f32d91aa546eec23b942a5a72203/bot/pagination.py#L239
My reasoning being that these are all somewhat "meta", I also wouldn't mind just making none of them in italics. I'd like to get another opinion first either way though.

**Comment by mbaruh** [comment]
Having placeholder values like "nothing to display" in italics and the rest without makes sense to me

**Review by wookie184 — APPROVED** [review]
Thanks!

**Review by MarkKoz — APPROVED** [review]

**Pull request merged**
