### PR TITLE
Change the class docstring on `ErrorHandler` cog to the imperative mood

### PR DESCRIPTION
**Pull request by Objectivitix**
## Description
I'm not even sure if this is worth a pull request, I was literally bored and while sifting through the source code I saw this lol
"Handles errors" should be "Handle errors" (in the imperative mood, as described by [the PyDis Styleguide](https://pythondiscord.com/pages/contributing/style-guide/#mood).)

Can we get a speedrun merge??

### CODE REVIEW

**Comment by Objectivitix** [comment]
speedrun!! let's try to get this pr merged in 8 hours

**Review by jb3 — APPROVED** [review]
:shipit:

**Review by vcokltfre — APPROVED** [review]
:shipit:

**Comment by jb3** [comment]
In the context of what a cog is, I don't think this is actually necessary, hence I'm revoking my approval and closing the PR.

There will always ever be only one ErrorHandler, if we move it to a generic package shared by Bot and Sir Lancebot then we could investigate changing docstrings to this form, but for this it doesn't make sense.

**Comment by Objectivitix** [comment]
PR speedrun any% [FAILED]
reason: joe had second thoughts
sad

**Comment by Objectivitix** [comment]
PR speedrun 100% approved, lint passed, then closed
10 minutes
we broke a record.

**Pull request closed without merging**
