### PR TITLE
New tags relating `module`s

### PR DESCRIPTION
**Pull request by CaedenPH**
Creates 3 new tags:
- `Module-not-found`
- `Modules`
- `Multiple-python`

Implements https://github.com/python-discord/meta/issues/191 and https://github.com/python-discord/meta/issues/189

### CODE REVIEW

**Comment by HassanAbouelela** [comment]
Thanks for the contribution, but were these approved or discussed? If so, please link the issue or discussion here. Generally we separate different features (tags in this case) in different PRs so it’s easier to review and track.

**Comment by CaedenPH** [comment]
> Thanks for the contribution, but were these approved or discussed? If so, please link the issue or discussion here. Generally we separate different features (tags in this case) in different PRs so it’s easier to review and track.

No, apologies, I was not aware that I had to create an issue. Should I close the pr and make an issue?

**Comment by HassanAbouelela** [comment]
No it’s alright, we’ll keep this open. I do however recommend opening issues for them on the meta repo and linking this PR to get people’s eyes on them.

**Comment by minalike** [comment]
Hi @CaedenPH, could I ask you to review this PR which I believe covers at least one of your suggested tag contents? https://github.com/python-discord/bot/pull/2230

**Comment by CaedenPH** [comment]
> Hi @CaedenPH, could I ask you to review this PR which I believe covers at least one of your suggested tag contents? https://github.com/python-discord/bot/pull/2230

Done, perhaps the information of that tag could be included/merged into my tags.

**Comment by AbooMinister25** [comment]
So, in regards to your last tag (`Multiple-python`), we already have a `dashmpip` tag which covers installing packages with `python -m pip`, and its relation to multiple python versions.

**Pull request closed without merging**
