### PR TITLE
Fix zen's negative indexing

### PR DESCRIPTION
**Pull request by francisdbillones**
Negative indexing starts at -1, not 0, meaning lower bound should be -1 * len(zen_lines), not -1 * upper_bound.
The current implementation means !zen -18 would spit out line 2, and not line 1.

### CODE REVIEW

**Comment by Xithrius** [comment]
@francisdbillones before creating a PR, please ask for approval from a core developer on the opened issue.

**Comment by francisdbillones** [comment]
Sorry, how would I do that? @eivl told me to create this pull request.

**Comment by Xithrius** [comment]
For this PR you would ask under the issue https://github.com/python-discord/bot/issues/1534.

**Review by mbaruh — APPROVED** [review]
Thanks!

As I said on the issue, -18 should indeed give the second line, not the first. The first line can be fetched with -19.

The fix however is correct.

**Review by ToxicKidz — APPROVED** [review]
:shipit:

**Pull request merged**
