### PR TITLE
Solved newline issue.

### PR DESCRIPTION
**Pull request by adhikariprajitraj**
Solved issue from #1232

### CODE REVIEW

**Comment by adhikariprajitraj** [comment]
@spitfire-hash Sorry, I was just messing around with the forked repo, and then (since I recently learned about git and GitHub) I did a mistake and then hastily I googled to do something about t and reverted it. Yes, the rest of the commits are useless, but I have no idea how to remove them.

**Comment by Den4200** [comment]
I'd recommend hard resetting to b0da6c01d995207a9dad6963a22ef0d217dc65bf locally, and then force pushing to this branch.
- `git reset --hard b0da6c01d995207a9dad6963a22ef0d217dc65bf`
- `git push --force origin master`

Please try not to do this again in the future, not just on our repositories, but anyone else's!

**Comment by adhikariprajitraj** [comment]
@Den4200 I am really sorry for the inconvenience, but can you please tell me if this PR can be merged or not(only the newline issue) or I have to open another PR, just for that since it has so many commits.

**Comment by Den4200** [comment]
@adhikariprajitraj Do as I said, and those extra commits will magically vanish.

**Comment by adhikariprajitraj** [comment]
@Den4200 Thank you. :)

**Comment by Akarys42** [comment]
Hey, thanks for the PR! Although, if we do add line continuations inside the docstrings, I feel like we should do that for all of our commands. Would you be interested by doing that?

**Comment by adhikariprajitraj** [comment]
@Akarys42 Sure, I will do it today.

**Comment by adhikariprajitraj** [comment]
@Akarys42  I did everything I could (rechecked twice). Can you please review and comment on my commit?

**Comment by Anubhav1603** [comment]
Your `pre-commit` checks are failing
Screenshot_2020-10-15-09-23-42-129
Have u installed `pre-commit`?

**Comment by adhikariprajitraj** [comment]
No, I haven't installed pre-commit. Do I need to install it in my computer?

**Comment by Anubhav1603** [comment]
Just run `pipenv run precommit`

**Comment by hedythedev** [comment]
@adhikariprajitraj have you looked at the [contributing guides](https://pythondiscord.com/pages/contributing)? It tells you that you need `pipenv` (`pip install pipenv`) and when setting up your development environment you use `pipenv run precommit` to install the hook, or you can run it manually using `pipenv run lint`, or just flake8 (the check that failed for this PR) using `pipenv run flake8`

you can refer [here](https://pythondiscord.com/pages/contributing/installing-project-dependencies/#installing-dependencies-with-the-command-line)

**Comment by adhikariprajitraj** [comment]
I installed it, ran it but do I have to hard reset everything and work on it again? It would be better if I can just hard reset the ./bot/exts/utils/bot.py @Akarys42 and @a 
Also, this git and this huge project are taking a toll on a beginner.

**Comment by hedythedev** [comment]
You don't have to reset it, just commit your new changes and push

**Comment by adhikariprajitraj** [comment]
@hedythedev After installing pre-commit I can no longer push changes to bot.py, I guess I have to give up.

**Comment by hedythedev** [comment]
The reason that you can't commit, I think is because the pre-commit checks for flake8 is failing, you will be able to commit and push once you've fixed the checks

**Comment by adhikariprajitraj** [comment]
@hedythedev I messed up again. I am really sorry for the trouble, but is there a way I can revert/reset the changes which were not supposed to be made according to precommit. All I did was just string formatting and I didn't even touch anything other.

**Comment by hedythedev** [comment]
> I'd recommend hard resetting to [b0da6c0](https://github.com/python-discord/bot/commit/b0da6c01d995207a9dad6963a22ef0d217dc65bf) locally, and then force pushing to this branch.
> 
> * `git reset --hard b0da6c01d995207a9dad6963a22ef0d217dc65bf`
> * `git push --force origin master`
> 
> Please try not to do this again in the future, not just on our repositories, but anyone else's!

you can use this again to reset the commits, but replace that sha (b0da6c0) with the sha of the last commit you want to reset to. Also i recommend you to learn and get familiar with git/github workflows https://try.github.io/

**Comment by Akarys42** [comment]
Hello @adhikariprajitraj.
It seems like your git history is quite messed up. Maybe you ran an auto formatter on the whole code at some point?

Also, it seems like you're working on your `master` branch, you should always work in another branch to avoid situations like that.

I'm closing this PR for now, feel free to delete your fork, fork again, and send a new PR, and I'll happily review it. If you have any question about the code or git itself, feel free to ask us in #dev-contrib!

**Pull request closed without merging**
