### PR TITLE
Stats: Implement rules stats

### PR DESCRIPTION
**Pull request by ks129**
Approved in #meta following [this conversation](https://canary.discordapp.com/channels/267624335836053506/429409067623251969/718449772737855559)

Adds a new statistic measuring the number of times a rule is fetched using the `!rules|site rules <rules...>` command.

### CODE REVIEW

**Comment by j03b** [comment]
@ks129 PR looks good, but can you edit the body to be a bit more descriptive?

**Comment by ks129** [comment]
@j03b Is now description better?

**Comment by j03b** [comment]
I've made a couple of adjustments, but yeah, that's better. PR body clarity is quite important for searching down the line & understanding full reasoning behind a change.

**Comment by kwzrd** [comment]
I agree with joe, by the way: the more relevant information you put into the PR description, the easier it'll be for us to review.

**Pull request merged**
