### PR TITLE
Fixed the code snippets limits

### PR DESCRIPTION
**Pull request by dolphingarlic**
- Made the line limit 15 (including lines between two snippets)
- Halved the char limit to be 1000

### CODE REVIEW

**Comment by vcokltfre** [comment]
I'd like to suggest before this gets reviewed that instead of halving the limit which may cut off stuff people want to see, if it gets past 1k characters the output is redirect to #bot-commands instead

**Review by jb3 — APPROVED** [review]

**Comment by jb3** [comment]
Whoops, approved, but I agree with @vcokltfre's comment.

**Review by vcokltfre — APPROVED** [review]
Looks great!

**Review by ChrisLovering — CHANGES_REQUESTED** [review]
You can get None from `bot. get_channel` if the cache isn't ready yet. Usually this problem is circumvented by awaiting the wait_until_guild_available event on the bot instance.

**Comment by ToxicKidz** [comment]
I don't think you'd receive the message event if the cache wasn't ready yet.

**Comment by ChrisLovering** [comment]
> I don't think you'd receive the message event if the cache wasn't ready yet.

Are you sure about that? I thought message events are still emitted while the cache is filling?

**Comment by ToxicKidz** [comment]
I guess it would be fine to just wait until the guild is ready just in case.

**Comment by vcokltfre** [comment]
> Are you sure about that? I thought message events are still emitted while the cache is filling?

Yep, message events can still be received before the ready event is received

**Review by ChrisLovering — APPROVED** [review]

**Pull request merged**
