### PR TITLE
Add unit tests for bot/rules/newlines.py

### PR DESCRIPTION
**Pull request by alberthdev**
Add some unit tests to validate behavior in bot/rules/newlines.py.
This covers both overall newline exceeding behavior, as well as
messages containing consecutive newlines within each message.

This test suite mimicks existing tests for attachment rules, as their
requirements are very similar.

Addresses: #602

### CODE REVIEW

**Comment by alberthdev** [comment]
Thanks for looking this over and providing feedback! Agreed that we could clarify the tests, and that we don't really test the case where the authors are different. Will take a look at updating these.

On a side note, I think it's probably worth testing the different user case as well in test_attachments.py - can update that as well if you want, though not sure if that should go into this PR or another one.

**Comment by MarkKoz** [comment]
I think it's OK if you also update the attachment tests in this PR.

**Comment by kwzrd** [comment]
I've some changes to the attachments test awaiting review in #655, so you might want to look at that if you're still planning to update the test cases. Sorry, did not realize you were planning to look at it too.

**Comment by lemonsaurus** [comment]
if @kwzrd is looking at the attachment tests, then there's no sense in having @alberthdev do it as well. Besides, it's been a month since there's been any activity here. Let's proceed with this PR without expanding its scope.

**Comment by lemonsaurus** [comment]
@alberthdev when will you have time to look at addressing the requests from @MarkKoz  ?

**Comment by alberthdev** [comment]
Have been busy with other things recently, but I hope to get back to this sometime soon. Hopefully by the end of the year.

**Comment by kwzrd** [comment]
Hi @alberthdev, could we get a status update on this?

**Comment by kwzrd** [comment]
Hello @alberthdev, since this PR has been stale for months now and we haven't been able to establish communication, I've decided to close it. There is a concurrent PR #733, which implements unit tests for all other antispam rules, and I think #602 can be addressed there as well.

I hope this is ok with you.

**Pull request closed without merging**
