### PR TITLE
Show when an infraction notified a user successfully via DM.

### PR DESCRIPTION
**Pull request by scragly**
I've added an envelope emoji to the infraction response message that indicates if an infraction successfully notified the user.

If the emoji is present, a DM was sent.
If it failed, or the infraction doesn't attempt to notify, it won't be present.

In the example below, the infractions to myself (Scragly) successfully send a DM notification. This includes the un-mute action also. For Eevee, the notification failed and so the emoji is not present.

dm-notification

### CODE REVIEW

**Comment by SebastiaanZ** [comment]
I really like this addition to the mod tools.

One small thing I'd do differently is to always include the feedback explicitly in the message instead of relying on the presence/absence of an icon. So, instead of showing the envelope on success and omitting it on failure, I'd always include the envelope, but with a check mark (e.g., :white_check_mark:) or a cross (e.g., :x:) next to it to indicate the success of the PM action.

The reason is that it makes the outcome apparent instead of having to notice an absence (so, relying on memory) when, say, you're handing out a warning.

However, other than that, I think this is a very welcome addition.

**Comment by SebastiaanZ** [comment]
That's fair, @scragly. I didn't really consider the perspective of having failures show up in public channels when writing my comment. I think your example would indeed be too distracting from the actual infraction.

My line of reasoning was this:

Sometimes infractions are handed out in #staff. In those cases, the only way for the user to actually receive the warning or the kick reason is by DM, so knowing if they did is important. However, moderators may not always remember to check and, when the DM actually failed, there's nothing in the bot response to remind them of it. So, in the situation where you actually want someone to notice that the DM failed, there's no explicit reminder in the bot response. 

However, your argument for not displaying failure to regular users may trump my argument for adding explicit feedback. I wonder if there's some middle ground, a subtle symbol that does remind the moderator that a DM wasn't sent, but that isn't really apparent to the "normal" user. I'm not sure what would be fitting, though.

Another option would be to have the bot mention the failure in mod-alerts with a mention of moderator who handed out the infraction (instead of the regular @everyone mention). That way, the "regular" uses will never know, but the moderator in question does get an explicit reminder of failure.

That's said, I'd support your addition as it is as well.

**Comment by heavysaturn** [comment]
how about implicit in the channel, explicit in the mod-logs?

**Comment by scragly** [comment]
Good idea @SebastiaanZ, I didn't think about sending the notice to modlog.
I'll adjust to add it in. Thanks!

**Comment by scragly** [comment]
Added the modlog message that pings the moderator who performed the command when a DM notification fails to send.

image

**Pull request merged**
