### PR TITLE
Separate message/embed deletion and reaction deletion emojis

### PR DESCRIPTION
**Pull request by kosayoda**
**Closes:** #297 and #514 

Currently, we use a red X for both message/embed deletion and reaction removal. Certain members are hence confused about the meaning of the reaction.

The PR adds a new emoji, `:trashcan:` for deletion of embed or message.
For regular pagination, the red X clears the reactions added by the bot, while the trashcan deletes the embed. The help cog has similar functionality.
image

Replies that use `wait_for_deletion` like `snekbox` now use the trashcan emoji instead of the red X, indicating that it is for message removal.
image

### CODE REVIEW

**Comment by MarkKoz** [comment]
How useful is the ❌ functionality really? I guess it can stop other people from messing with the pagination? I just don't see that get used much and it may be confusing being seen together with a trash can.

**Comment by kosayoda** [comment]
I'm not too sure about that too, there would be cases where you'd not want the emojis there but still want to read the message.

**Comment by ikuyarihS** [comment]
We do automatic reactions removal after a certain period of time iirc, so won't the ❌ be redundant in that case? I can see the confusion between ❌ and `:trashcan:` since both are used to `remove`.

**Comment by lemonsaurus** [comment]
@kosayoda I think it would be clearer if we just removed the :x: now that we're using the trashcan.

@ikuyarihS makes a good point about automatic removals - the reactions should just time out after a while (and get removed when they do). I think they already do this for the paginator.

This PR looks good to merge once that's been addressed.

**Comment by MarkKoz** [comment]
@kosayoda any updates on this?

**Comment by scragly** [comment]
A conflict was introduced here due to #681

**Pull request merged**
