### PR TITLE
Add GitHub codespaces support

### LINKED ISSUE #1169: Fully supporting GitHub codespaces
## What are codespaces?

In their latest Satellite, GitHub announced the launch of Codespaces, an online development environment running VSC, fully integrated with GitHub. As the time of writing this, the feature is in public beta. You can read more about it [here](https://github.com/features/codespaces).

## What needs to be done?
I’ve tried this recently to review a PR, it was pretty great, although some manual setup was still required, like installing `pipenv`, syncing it and installing `docker-compose` (The docker engine was already included). Thankfully, GitHub is providing a `.devcontainer` config file, to automate all this process. The documentation is [here](https://docs.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project).

### PR DESCRIPTION
**Pull request by Akarys42**
Not so much to see here for now, I’ll add more later. 

Closes #1169

### CODE REVIEW

**Comment by Akarys42** [comment]
I won't have time to finish this, if someone feels up to the task, feel free to continue the work here!

**Comment by Xithrius** [comment]
@jb3 you have experience with workspaces, right? 

Do you think you could do this, or link any useful documentation for someone to pick this PR up?

**Comment by jb3** [comment]
Very rough experience! Probably not enough to be able to complete this fully though sadly, at least not in the immediate future.

**Comment by Xithrius** [comment]
If you're experienced enough to take over this PR, do it.

**Pull request closed without merging**
