### PR TITLE
Add range-len tag

### PR DESCRIPTION
**Pull request by swfarnsworth**
This would be a message we could whip out when we see `range(len(...))` for loops during help sessions. I intentionally left out a lot of interesting details to keep the message concise.

I recall there being a RealPython article about "pythonic loops" and was hoping to link to it, but it looks like it's now paid content. I saw that our guides are under construction and I'd be happy to write a guide on loops with an emphasis on pythonicness.

I don't know that linking to the official Python docs is a digestible resource for some learners, especially those who don't have experience in other languages, so I'm very much open to alternatives for those.

### CODE REVIEW

**Comment by swfarnsworth** [comment]
@kwzrd I see what you're saying about displaying the REPL output. I think people who use `range(len(...))` are familiar with iteration in general (and probably use it that way in a C-style language); if the concept of iteration itself is where they're struggling, they probably don't know why they have `range(len(...))` in their code, and a tailored approach would be needed to teach them that concept. If we find that the current message isn't effective, we could see if a REPL display is what would trigger the aha moment for them.

**Comment by Den4200** [comment]
Looks good! However, since we do have `!zip` and `!enumerate` tags, maybe they could be mentioned in this tag?

**Comment by swfarnsworth** [comment]
@Den4200 Do we have any other messages that suggest that you run a command to get another message? The idea sounds a bit weird to me, but our messages would probably be more informative for our intended audience than the Python docs.

**Comment by Den4200** [comment]
After some discussion in `#organisation`, it looks like the tag is ready to go.

**Pull request merged**
