### PR TITLE
Suppress 403 error when sending DEFCON reject DM

### PR DESCRIPTION
**Pull request by MarkKoz**
Sentry Issue: [BOT-37](https://sentry.io/organizations/python-discord/issues/2437630529)

403 occurs if the user has DMs disabled. The specific code is 50007, but I don't think 403 would be raised for any other reason here, so I didn't check the code explicitly. If someone has more insight on this, please comment.

### CODE REVIEW

**Comment by NIRDERIi** [comment]
Wouldn't it require to handle discord.HTTPException? Or I totally misunderstood you

**Comment by wookie184** [comment]
> 
> 
> Wouldn't it require to handle discord.HTTPException? Or I totally misunderstood you

`discord.Forbidden` is a subclass of `discord.HTTPException`, httpexception could be any response from the api saying it didn't work, e.g. a random error with the Discord API, while `Forbidden` is more specific, and as in that part of the code we only want to catch disabled DMs, I believe `Forbidden` is correct.

If you were instead referring to replacing the general `Exception` with `discord.HTTPException`, then yeah, that should probably work from what I can see, although the logger logs an exception in that instance anyway, and as the comment says, sending the DM is less important than kicking the user, so we want to avoid the code failing at that point as much as possible.

**Review by wookie184 — APPROVED** [review]
I can't think of any other reason the bot should get a `Forbidden` error here. lgtm

**Comment by mbaruh** [comment]
Just for my understading, the issue here is that `log.exception` opens an issue on Sentry? as functionality-wise it seems to be working fine already.

**Comment by MarkKoz** [comment]
> 
> 
> Just for my understanding, the issue here is that `log.exception` opens an issue on Sentry? as functionality-wise it seems to be working fine already.

The issue being fixed is 403 Forbidden errors being logged as exceptions and creating issues on Sentry.

**Pull request merged**
