### PR TITLE
Check infraction reason isn't None before shortening it

### PR DESCRIPTION
**Pull request by MarkKoz**
With the recent changes to truncate reasons, infractions will fail to apply if a reason isn't provided. The fix is to only shorten the reason if it isn't None.

### CODE REVIEW

**Comment by MarkKoz** [comment]
@kosayoda IMO, the optional type annotations are mostly unnecessary and hurt readability. The reason already has a default value of `None`, which should be enough to clue readers in that it's optional. I already have a commit I can push with the annotations removed.

**Comment by SebastiaanZ** [comment]
I like type hints with the explicit `Optional` type hint.

**Comment by MarkKoz** [comment]
OK. Should there be extra indentation for the parameters? PEP 8 suggests this because it argues that they'd otherwise not be distinguishable from the function body. However, they don't put the closing parenthesis and colon on a separate line, which I argue does adequately distinguish parameters from the body along with the mandatory docstring.

**Comment by SebastiaanZ** [comment]
I'm honestly not married on either (the `Optional` type hint) and/or the indentation we choose, but my personal preference is to use the `Optional`, but not add additional indentation.

If you feel like it greatly increases readability by leaving the `Optional` out, I'm fine by that as well; what's the general style throughout the bot? I personally probably always add the `Optional` explicitly.

**Comment by MarkKoz** [comment]
I generally agree that it should be explicit. But I think it's also okay to break consistency to improve readability. Ultimately, these type annotations are supposed to help us, not hurt us. I honestly find most parameter splitting to be ugly, like in this case, so I'd rather avoid it. I also find long function signatures ugly, but what can we do 🤷 .

I'll leave the explicit type hints but remove the extra indentation since it's more consistent with other code. We should consider updating our [style guide](https://pythondiscord.com/pages/contributing/style-guide/#bracket-and-item-arrangement) if this is the consensus.

**Pull request merged**
