### PR TITLE
Add more information to helpdm embeds.

### PR DESCRIPTION
**Pull request by Qwerty-133**
Implements part 1 of #1960

### CODE REVIEW

**Review by MarkKoz — CHANGES_REQUESTED** [review]
I'd rather see most, if not all the help dm code in the `_messages.py` file or some new module rather than in the cog's file. The cog already has quite a lot going on, and we should try to avoid making it even harder to read.

**Comment by Xithrius** [comment]
@Qwerty-133 What's your status on this PR?

Thanks!

**Comment by Qwerty-133** [comment]
Hey @Xithrius! I'll be finishing this up soon, thanks for the reminder

**Comment by Xithrius** [comment]
@Qwerty-133 Hey, been a while. Thoughts on reviving this PR?

Thanks!

**Comment by wookie184** [comment]
Since this is quite old and there are a lot of conflicts since this was made before we moved to forum help channels, i'll close this. It probably also needs some more discussion about what parts are still relevant/need changing on the issue before continuing.

**Pull request closed without merging**
