### PR TITLE
Use wait_for_deletion from bot/utils/messages.py rather than help_cleanup

### LINKED ISSUE #1122: Cleanup inconsistency
`bot/cogs/help.py` uses its own message cleanup (`help_cleanup`) rather than the premade message cleanup (`wait_for_deletion`) on `bot/utils/messages.py`. I reviewed and edited the code, and there is no difference.

### PR DESCRIPTION
**Pull request by AtieP**
Fixes #1122. `bot/cogs/help.py` uses its own cleanup called `help_cleanup` rather than the premade cleanup (`wait_for_deletion`) from `bot/utils/messages.py`. This is an inconsistency because all messages with cleanup use `wait_for_deletion`.

### CODE REVIEW

**Comment by MarkKoz** [comment]
Interestingly, paginated outputs won't show a delete emoji if there's only one page (e.g. `!help Moderation`). But that's a separate issue.

**Comment by AtieP** [comment]
@MarkKoz Done, I fixed that. And interesting, on the `setup` function, this message `Cog loaded: Help` is logged as an information message, but there is no need, because on the `bot/bot.py` file, `add_cog` was overrided to log what cog was loaded.

**Comment by MarkKoz** [comment]
Feel free to remove that log message too.

**Review by ikuyarihS — APPROVED** [review]
Looks good to me!

**Pull request merged**
