### PR TITLE
feat: use new markdown feature in new help channel message

### LINKED ISSUE #2646: Use new markdown features in messages
The bot should use new markdown features instead hard coded unordered lists for example:

image

uses `•` it can be replaced by `-` and markdown would format it same way

### PR DESCRIPTION
**Pull request by DownDev**
Closes #2646

### CODE REVIEW

**Comment by ChrisLovering** [comment]
Does this PR cover everything required in that issue? If not, we shouldn't mark this PR as closing that issue.

**Comment by DownDev** [comment]
I guess i can go over commands and see if there is something to change.

**Comment by DownDev** [comment]
@ChrisLovering Actually many tags dont use correct syntax for markdown. Also the `!patreon supporters` command is what i found for now.

All of the above are using the `•` instead of `-`

**Review by Xithrius — APPROVED** [review]
LGTM. Might want to look around again after this branch is updated.

**Review by ChrisLovering — APPROVED** [review]

**Pull request merged**
