### PR TITLE
fixed typos in tags embed. 

### PR DESCRIPTION
**Pull request by Hashed0719**
Fixed typos discussed in #2583. Removed unnecessary merge commit in previous(closed) PR #3001 .

### CODE REVIEW

**Review by GriceTurrble — APPROVED** [review]

**Review by GriceTurrble — APPROVED** [review]

**Comment by Hashed0719** [comment]
@GriceTurrble sorry for inconvenience but would you be able to reverify the changes if a rebase and recommit in this PR only or do i have to open a new one ?

**Comment by GriceTurrble** [comment]
> @GriceTurrble sorry for inconvenience but would you be able to reverify the changes if a rebase and recommit in this PR only or do i have to open a new one ? 

Either way, I suppose?

**Comment by Hashed0719** [comment]
@GriceTurrble done.

**Review by ChrisLovering — APPROVED** [review]

**Review by GriceTurrble — APPROVED** [review]

**Review by vivekashok1221 — APPROVED** [review]
LGTM.

**Review by hedyhli — APPROVED** [review]
thanks!

**Pull request merged**
