### PR TITLE
Don't log threads in admin channels

### PR DESCRIPTION
**Pull request by ChrisLovering**
This change disables the mod-log for any changes to threads in channels that mods don't have read perms to.

### CODE REVIEW

**Review by HassanAbouelela — APPROVED** [review]
Love it

**Review by mbaruh — COMMENTED** [review]
Considering what this PR tries to achieve I'm not sure it makes sense to have the channel mention in the log

**Comment by ChrisLovering** [comment]
> Considering what this PR tries to achieve I'm not sure it makes sense to have the channel mention in the log

It's a trace log, purely for dev testing, since I wanted a way to ensure it was being ignored.

**Review by Akarys42 — APPROVED** [review]
Good stuff

**Pull request merged**
